[package]
name = "perseus-macro"
version = "0.5.0"
edition = "2021"
autotests = false
description = "The Perseus macros."
authors = ["arctic_hen7 <arctic_hen7@pm.me>"]
license = "MIT"
repository = "https://github.com/framesurge/perseus"
homepage = "https://framesurge.sh/perseus"
readme = "../../README.md"
keywords = ["wasm", "frontend", "webdev", "ssg", "ssr"]
categories = [
    "wasm",
    "web-programming",
    "development-tools",
    "asynchronous",
    "gui",
]

[lib]
proc-macro = true

[dependencies]
quote = "1"
syn = "2"         # Needs to remain on v1 until `darling` updates
proc-macro2 = "1"
darling = "0.21"

[dev-dependencies]
trybuild = { version = "1.0", features = ["diff"] }
sycamore = "^0.9.1"
serde = { version = "1", features = ["derive"] }
